committees/urls.py
from django.conf.urls.defaults import *
from django.conf import settings

from committees import views

urlpatterns = patterns('committees.views',
    url (r'^$', view=views.index, name='cm-index', ),
    url (r'^(?P<slug>[-\w]+)/officer/(?P<office_slug>[-\w]+)/$', view=views.term_detail, name='cm-term-detail', ),
    url (r'^(?P<slug>[-\w]+)/officer/(?P<office_slug>[-\w]+)/(?P<start_year>[\d]+)/$', view=views.term_detail, name='cm-term-archive-year', ),
    url (r'^(?P<slug>[-\w]+)/$', view=views.group_detail, name='cm-group-detail', ),
    url (r'^(?P<slug>[-\w]+)/meetings/$', view=views.group_meeting_list, name='cm-group-meeting-list', ),
    url (r'^(?P<slug>[-\w]+)/meetings/(?P<year>[\d]+)/$', view=views.group_meeting_archive_year, name='cm-group-meeting-archive-year', ),
    url (r'^(?P<slug>[-\w]+)/meetings/(?P<year>[\d]+)/(?P<month>[\w]+)/$', view=views.group_meeting_detail, name='cm-meeting-detail', ),
    url (r'^(?P<slug>[-\w]+)/meetings/(?P<year>[\d]+)/(?P<month>[\w]+)/print/$', view=views.group_meeting_detail, name='cm-meeting-print', ),
    
)

committees/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from datetime import datetime, date
from django.contrib.localflavor.us.models import PhoneNumberField
from django.contrib.auth.models import User
from markup_mixin.models import MarkupMixin
from committees.managers import BoardManager, ActiveTermManager, ActiveGroupManager, ApprovedManager

from django_extensions.db.models import TimeStampedModel, TitleSlugDescriptionModel
from eventy.models import EventTime
from photologue.models import ImageModel, Photo
from simple_history.models import HistoricalRecords

class GroupType(TitleSlugDescriptionModel):
    '''Group type model.

    Allows catering the group type to how orgs are organized into governing groups.
    
    e.g. Governing board, Ad-hoc committee, Congregation'''
    order = models.IntegerField(_('Order'), max_length=2)

    class Meta:
        verbose_name = _('Group type')
        verbose_name_plural = _('Group types')
        ordering = ('order', 'title',)

    def __unicode__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        return ('cm-group-type-detail', None, {'slug': self.slug})

class Group(TimeStampedModel, TitleSlugDescriptionModel):
    '''Group model.

    Manages the various types of governing groups in an organization. (e.g. Governing Board, Music Committee, etc...)
    '''

    order=models.IntegerField(_('Order'), max_length=2, help_text='Used to order groups in a list. Set all ranks the same to sort by alpha.')
    type=models.ForeignKey(GroupType)
    active=models.BooleanField(_('Active'), default=True)
    formed_on=models.DateField(_('Formed on'), blank=True, null=True)
    disbanded_on=models.DateField(_('Disbanded on'), blank=True, null=True)
    adhoc=models.BooleanField(_('Ad-hoc'), default=False, help_text='Is this is an ad-hoc group?')
    members=models.ManyToManyField('Person', related_name='members', blank=True, null=True, help_text='Non-term limited members of the group.')
    past_members=models.ManyToManyField('Person', related_name='past_members', blank=True, null=True, help_text='Non-term limited members who have left the group')
    #deceased_members = models.ManyToManyField('Person', related_name='deceased_members', blank=True, null=True, help_text='Non-term limited members who have passed away')
    special_title=models.CharField(_('Special title'), max_length=255, blank=True, null=True, help_text='If the auto-generated name for the group makes no sense.')
    ex_officio = models.BooleanField(_('Ex-Officio'), default=False, help_text='Does this group fall under the ex-officio officer rules?')

    objects=models.Manager()
    active_objects=ActiveGroupManager()

    def __init__(self, *args, **kwargs):
        super(Group, self).__init__(*args, **kwargs)
        self._eo_members = []

    class Meta:
        verbose_name = _('Group')
        verbose_name_plural = _('Groups')

    def __unicode__(self):
        if self.special_title:
            return u'%s' % self.special_title
        else:
            return u'%s %s' % (self.title, self.type)

    @models.permalink
    def get_absolute_url(self):
        return ('cm-group-detail', None, {'slug': self.slug})

    def save(self, *args, **kwargs):
        if self.disbanded_on and self.active:
            self.active = False
        super(Group, self).save(*args, **kwargs)

    @property
    def current_terms(self):
        return Term.active_objects.filter(group=self)

    @property
    def past_terms(self):
        objects=[]
        for t in Term.objects.all().filter(group=self):
            if not t in Term.active_objects.all().filter(group=self):
                objects.append(t)
        return objects

    @property
    def exofficio_members(self):
        if not self._eo_members:
            if self.ex_officio:
                for o in Office.objects.filter(ex_officio=True):
                    if o.current and (o.current not in self.current_terms):
                        self._eo_members.append(o.current)
        return self._eo_members

class GroupPhoto(ImageModel):
    '''Group photo model.

    Represents a photo of a governing group at a specific time.'''
    group=models.ForeignKey(Group)
    year=models.IntegerField(_('Year'), max_length=4)
    caption=models.TextField(_('Caption'), blank=True, null=True)

    class Meta:
        verbose_name = _('Group photo')
        verbose_name_plural = _('Group photos')
        get_latest_by='year'

    def __unicode__(self):
        return u'%s photo of %s' % (self.year, self.group)
    
class Office(TimeStampedModel, TitleSlugDescriptionModel):
    '''
    Office model.

    Holds all the various office types, mostly just drawn from django-extension 
    mixins. Designed to take care of pres, vp, sec, tres type positions.

    '''
    group=models.ForeignKey(Group)
    order=models.IntegerField(_('Office order'), max_length=2)
    ex_officio=models.BooleanField(_('Ex-Officio'), default=False,
    help_text='An ex-officio office is, by default, a member of all committees, unless stated.')
    
    class Meta:
        verbose_name = _('Office')
        verbose_name_plural = _('Offices')
        ordering = ('order', 'group',)

    def __unicode__(self):
        return u'%s of %s' % (self.title, self.group)

    @property
    def previous(self):
        current = past = None
        terms = self.term_set.all().order_by('-end')
        i=1
        for t in terms:
            try:
                past = terms[i]
            except:
                return None
            if (t.person != past.person) and not t.active:
                return past
            i+=1
        return self.term_set.all().order_by('-end')[1]

    @property
    def current(self):
        terms =[]
        for t in self.term_set.all().order_by('-end'):
            if t.active:
                terms.append(t)
        if len(terms) == 1:
            return terms[0]
        else:
            for t in terms:
                t.office.title = "Co-"+t.office.title
            return terms

class Term(TimeStampedModel):
    group = models.ForeignKey(Group)
    start = models.DateField(_('Start'))
    end = models.DateField(_('End'), blank=True, null=True)
    office = models.ForeignKey(Office, blank=True, null=True)
    alternate = models.BooleanField(_('Alternate'), default=False)
    person=models.ForeignKey('Person', blank=True, null=True)
    
    objects = models.Manager()
    board_members = BoardManager()
    active_objects = ActiveTermManager()

    class Meta:
        verbose_name = _('Term')
        verbose_name_plural = _('Terms')
        ordering = ('-office','start',)
        get_latest_by = 'start'
   
    @property
    def active(self):
        status=False
        if self.start <= date.today():
            if self.end:
                if self.end >= date.today():
                    status = True
            else:
                status=True
        return status
    
    @property
    def length(self):
        if self.end: return (self.end.year - self.start.year)
        else: return None
    
    @property
    def tenure(self):
        tenure = 0
        terms = Term.objects.filter(person=self.person)
        for t in terms:
            if t.length:
                tenure += self.length
            elif not t.end:
                tenure += datetime.now().year - self.start.year

        return tenure

    @property
    def officer(self):
        if self.office: return True
        else: return False

    def __unicode__(self):
        if self.officer: desc=self.office
        else: desc=u'%s member' % (self.group)
        
        if self.alternate: str=u'%s - alternate (%s)' % (self.person, self.start.year)
        else: str=u'%s - %s (%s)' %(self.person, desc, self.start.year)
        return str

    @models.permalink
    def get_absolute_url(self):
        if self.office: return ('cm-term-detail', None, {'slug': self.group.slug, 'office_slug': self.office.slug, })
        else: return None

class Person(models.Model):
    """Person model."""
    GENDER_CHOICES = (
        (1, 'Male'),
        (2, 'Female'),
    )
    first_name = models.CharField(_('First name'), blank=True, max_length=100)
    middle_name = models.CharField(_('Middle name'), blank=True, max_length=100)
    last_name = models.CharField(_('Last name'), blank=True, max_length=100)
    title = models.CharField(_('Title'), blank=True, max_length=100)
    slug = models.SlugField(_('Slug'), unique=True)
    user = models.ForeignKey(User, blank=True, null=True, help_text='If the person is an existing user of your site.')
    gender = models.PositiveSmallIntegerField(_('Gender'), choices=GENDER_CHOICES, blank=True, null=True)
    member = models.BooleanField(_('Member'), default=True, help_text='Is this person a member of the organization?')
    phone = PhoneNumberField(_('Phone'), blank=True, null=True)
    email = models.EmailField(_('Email'), blank=True, null=True)
    photo = models.ForeignKey(Photo, blank=True, null=True)
    bio = models.TextField(_('Biography'), blank=True, null=True)

    class Meta:
        verbose_name = _('person')
        verbose_name_plural = _('people')
        ordering = ('last_name', 'first_name',)

    def __unicode__(self):
        return u'%s' % self.full_name

    @property
    def full_name(self):
        return u'%s %s' % (self.first_name, self.last_name)

    @property
    def on_board(self):
        for t in self.term_set.all():
            if t.group.order == 10:
                return True

    @models.permalink
    def get_absolute_url(self):
        return ('cm-person-detail', None, {'slug': self.slug})


class Meeting(MarkupMixin, TimeStampedModel, EventTime):
    '''
    Meeting model.

    A general meeting model. 
    '''
    group = models.ForeignKey(Group)
    agenda = models.TextField(_('Agenda'), blank=True, null=True)

committees/templates/committees/base.html
{% extends "base.html" %}

{% block extra_headers %}
<link rel="stylesheet" type="text/css" media="print" href="{{ MEDIA_URL }}css/print.css" />
{% endblock %}

{% block menu-class %}gov{% endblock %}

committees/templates/committees/group_detail.html
{% extends "committees/base.html" %}
{% block page-class %}gov{% endblock %}
{% block title %}{{object}} at {% endblock %}

{% load humanize markup typogrify %}

{% block body %}
  <div class="grid_12 page">
    <h2>Governance</h2>
  </div>

  <div class="grid_4">
    <h3>{{object}}</h3>
    {{object.description|typogrify|markdown}}
  </div>

  <div class="grid_4">
  {% if members or object.members %}
  <h3>Members</h3>
  <ul class="board">
    {% if object.current_terms %}
    {% for t in object.current_terms %}
    <li>{% if t.alternate %}<span class="alt">Alt.</span> {% endif %}{{t.office.title}}<a href="{{t.get_absolute_url}}"> {{t.person}}</a> {{m.start_date|date:"Y"}}</li>
    {% endfor %}
    {% endif %}
    {% if object.members.all %}
    {% for p in object.members.all %}
    <li>{% if p.email %}<a href="mailto:{{p.email}}">{% endif %}{{p}}{% if p.email %}</a>{% endif %}</li>
    {% endfor %}
    {% endif %}
  </ul>
  {% endif %}
</div>

<div class="grid_4 last">
    {% if object.meeting_set.all %}
    <h3>Meetings of the {{object}}</h3>
    <ul>
    {% for m in object.meeting_set.all|dictsortreversed:"start" %}
    <li><a href="{{m.get_absolute_url}}">{{m.start|naturalday}}</a></li>
    {% endfor %}
    </ul>
    {% endif %}
  </div>
{% endblock %}

committees/templates/committees/index.html
{% extends "committees/base.html" %}
{% block page-class %}gov{% endblock %}
{% block title %}Governance at {% endblock %}
{% load humanize markup typogrify committee_tags eventy_tags %}

{% block body %}
  <div class="grid_12">
	  <h2>Governance</h2>
  </div>

  <div class="grid_7">
    {% get_committee_groups active order 10 as board %}
    <h3>{{board}}</h3>
    <img class="governance" src="{{board.groupphoto_set.latest.get_display_url}}" />
    {{board.groupphoto_set.latest.caption|typogrify|markdown}}
    {{board.description|typogrify|markdown}}

  </div>

  <div class="grid_2 ">
    <h3>Members</h3>
    {% for t in board.current_terms %}
    {% if forloop.first %}<ul class="board">{% endif %}
        <li>{% if t.office %} <span class="office">{{t.office.title}}</span><br/> {% endif %}<span class="person">{{t.person}}</span>{% if t.alternate %} <span class="alt">Alt.</span>{% endif %}</li>
    {% if forloop.last %}</ul>{% endif %}
    {% endfor %}
    <p><a href="{{board.get_absolute_url}}">View agendas and minutes</a></p>
  </div>
  <div class="grid_3 last">
    <h3>Meetings</h3>
    <ul>
    {% for m in past_meetings %}
    <li><a href="{{a.get_absolute_url}}">{{m.start|naturalday}}</a></li>
    {% endfor %}
    </ul>
  </div>

  <div class="grid_12 last">

    <h3>Committees</h3>
    {% get_committee_groups active order 20 as committees %}
    {% if committees %}
    {% for c in committees %}
    <dl class="committee" id="c.slug">
      <dt><a href="{{c.get_absolute_url}}">{{c}}</a></dt>
      {% for t in c.current_terms %}
      <dd class="{{t.office.title}} member"><em>{{t.office.title}}&nbsp;{{t.person}}</em></dd>
      {% endfor %}
      {% for p in c.members.all %}
      <dd class="member">{{p}}</dd>
      {% endfor %}
    </dl>
  {% endfor %}
  {% endif %}
</div>
{% endblock %}

committees/templates/committees/meeting_detail.html
{% extends "committees/base.html" %}
{% block page-class %}gov{% endblock %}
{% load humanize markup typogrify committee_tags %}
{% block title %}{{object.title}} meeting of {{object.start|naturalday}} at {% endblock %}

{% block body %}
  <div class="grid_12 last">
    <h2>Governance</h2>
  </div>

  <div class="grid_8" >
  {% get_committee_minutes for object as minutes %}
  {% if object %}
  <h3>{{object.title}} {% if minutes and board_member %}{% if minutes.draft %}DRAFT{% endif %} Minutes{% else %}Agenda{% endif %} of the {{object.group}}</h3>
  <h3>{{object.start|naturalday}} {{object.start|time:"f a"}}</h3>

  {% if minutes and board_member %}  
  {% if minutes.call_to_order %}<p>Meeting called to order at {{minutes.call_to_order|time:"f a"}} in {{object.location}}.</p>{% endif%}

  {{minutes.rendered_content|typogrify}}
  {% if object.get_next_meeting %}
  <p><a href="{{object.get_next_meeting.get_absolute_url}}">Next meeting at {{ object.get_next_meeting.start|naturalday }} at {{ object.get_next_meeting.start|time:"f a" }}</a></p>
  {% endif %}
  {% if minutes.adjournment %}<p>Meeting adjourned at {{minutes.adjournment|time:"f a"}}.</p>{% endif %}

  {% if minutes.signed %}
  <p>Respectfully submitted,</p>
  <p>{{ minutes.signed }} {% if minutes.signed.term_set.all %}{% for t in minutes.signed.term_set.all %}{% if forloop.first %}, {{t.office.title}}{% endif %}{% endfor %}{% endif %}</p>
  <p>{{ minutes.signed_date|naturalday }}</p>
  {% endif %}

  {% else %}
  {% if object.meeting.agenda %}
  <div class="agenda">
  {% if object.meeting.agenda %}
  <h4>Proposed agenda</h4>
  {{object.meeting.agenda|typogrify|markdown}}
  {% else %}
  <p>This meeintg does not yet have an agenda set.</p>
  {% endif %}
  </div>
  {% endif %}
  {% endif %}
  {% endif %}
</div>

<div class="grid_4 last">
    {% if minutes and board_member %}
  <div class="box">
  <h3>Members present</h3>
  <ul>
  {% for t in minutes.members_present.all %}
  <li>{{t.person}}{% if t.office %}, {{t.office.title}}{%endif %}</li>
  {% endfor %}
  </ul>

  {% if minutes.others_present %}
  <h3>Others present</h3>
  <ul>
  {% for g in minutes.others_present.all %}
  <li>{{g}}</li>
  {% endfor %}
  </ul>
  <hr />
  </div>
  {% else %}
  <hr />
  </div>
  {% endif %}
  {% endif %}
</div>

{% endblock %}

committees/templates/committees/minutes_detail.html
{% extends "gov/base.html" %}
{% block page-class %}gov{% endblock %}
{% load humanize markup typogrify %}
{% block title %}{{object.title}} meeting of {{object.start|naturalday}} at {% endblock %}

{% block content %}
  <div class="grid_12">
    <h2>Governance</h2>
  </div>

  {% if object %}
  <h3>Minutes of the {{object.meeting.title}} meeting</h3>
  <div class="minutes">
  <p>{{object.meeting.start|naturalday}} {{object.meeting.start|time:"h:m"}}</p>
  {{object.content|typogrify|markdown}}
  </div>
  {% endif %}
{% endblock %}

committees/templates/committees/sermon_detail.html
{% extends "sermon/base.html" %}
{% block page-class %}sermons{% endblock %}
{% block title %}Sermon: {{sermon.title}} at {% endblock %}
{% load markup humanize typogrify %}

{% block body %}
<div class="grid_12">
<h2>{{sermon.title}}</h2>
<h3 class="alt">A sermon by {{sermon.speaker}}</h3>
<h3>{{sermon.date|naturalday}}</h3>
</div>

<div class="grid_8 sermon-body">
  <dl class="audio-player" id="sermon-audio-{{sermon.id}}">
    <dt>Watch the sermon</dt>
    <dd>  
	  This could have an audio player.
    </dd>
  </dl>
  {{sermon.body|typogrify|markdown}}
  <p><a href="{% url sr-index %}">Read more sermons</a></p>
</div>

<div id="sidebar" class="grid_3 box ">
<h2>Readings</h2>
<ol>
{% for reading in sermon.readings.all %}
  <li><h5>From {{reading.source}}</h5>
  <div class="reading" id="reading-{{reading.id}}">
    {{reading.text|typogrify|markdown}}
  </div></li>
{% endfor %}
</ol>
</div>

{% endblock %}

committees/templates/committees/term_detail.html
{% extends "committees/base.html" %}
{% block page-class %}gov{% endblock %}
{% block title %}{{term}} at {% endblock %}

{% block content %}
{% load humanize markup typogrify %}
  <div class="grid_12">
    <h2>Governance</h2>
  </div>

  {% if term %}
  <h3>{{term.office.title}} of the {{term.office.group}}</h3>
  <p>{{term.length}} year term beginning {{term.start.year}}</p>
  <h4>Currently held by</h4>
  <ul>
      <li>{{term.person}}</li>
      <li>Phone: {{term.person.phone}}</li>
      <li>Email: {{term.person.email|urlize}}</li>
  </ul>
  {% endif %}
{% endblock %}